### ISSUE TITLE
Peer to Peer Code Review

### ISSUE THREAD

**Issue by frankopkusianwar** [frankopkusianwar/Zatix#1]

**Comment by mariosknl** [comment]
Great work so far Frank. I like your approach. Keep in mind about the static units when you will set the responsiveness. I'm not sure about the image format though. I saw this files with .webp extension so try to see if it's better to replace the images with their link.

**Comment by teekaytech** [comment]
Nice job so far. 

I will suggest that, since you have decided to use bootstrap, you should use more of bootstrap components (card components, etc) and classes, just to make your work easier.

**Comment by mbabaliiryn** [comment]
Nice Progress so far. keep it up.
